'use client'

import { useQuery } from '@/utils/api'
import { USDC_MINT } from '@/utils/constants'
import { useEffect, useMemo, useState } from 'react'
import { StonkCard } from './components/stonk-card'
import { IStockInfo } from './stonks.models'

// xStocks from https://xstocks.fi/products
// Note: keep symbols consistent with product tickers, names are human-friendly
// For items where mint is unknown, leave mint as empty string '' and we'll fill later.
const STOCK_DATA: IStockInfo[] = [
  {
    mint: 'XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7',
    symbol: 'ABTx',
    name: 'Abbott xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie',
    symbol: 'ABBVx',
    name: 'AbbVie xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU',
    symbol: 'ACNx',
    name: 'Accenture xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN',
    symbol: 'GOOGLx',
    name: 'Alphabet xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg',
    symbol: 'AMZNx',
    name: 'Amazon xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb',
    symbol: 'AMBRx',
    name: 'Amber xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp',
    symbol: 'AAPLx',
    name: 'Apple xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV',
    symbol: 'APPx',
    name: 'AppLovin xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU',
    symbol: 'AZNx',
    name: 'AstraZeneca xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP',
    symbol: 'BACx',
    name: 'Bank of America xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x',
    symbol: 'BRK.Bx',
    name: 'Berkshire Hathaway xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo',
    symbol: 'AVGOx',
    name: 'Broadcom xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts',
    symbol: 'CVXx',
    name: 'Chevron xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1',
    symbol: 'CRCLx',
    name: 'Circle xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf',
    symbol: 'CSCOx',
    name: 'Cisco xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ',
    symbol: 'KOx',
    name: 'Coca-Cola xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu',
    symbol: 'COINx',
    name: 'Coinbase xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8',
    symbol: 'CMCSAx',
    name: 'Comcast xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw',
    symbol: 'CRWDx',
    name: 'CrowdStrike xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV',
    symbol: 'DHRx',
    name: 'Danaher xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy',
    symbol: 'DFDVx',
    name: 'DFDV xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH',
    symbol: 'LLYx',
    name: 'Eli Lilly xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh',
    symbol: 'XOMx',
    name: 'Exxon Mobil xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc',
    symbol: 'GMEx',
    name: 'Gamestop xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re',
    symbol: 'GLDx',
    name: 'Gold xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1',
    symbol: 'GSx',
    name: 'Goldman Sachs xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3',
    symbol: 'HDx',
    name: 'Home Depot xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2',
    symbol: 'HONx',
    name: 'Honeywell xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM',
    symbol: 'INTCx',
    name: 'Intel xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr',
    symbol: 'IBMx',
    name: 'International Business Machines xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn',
    symbol: 'JNJx',
    name: 'Johnson & Johnson xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C',
    symbol: 'JPMx',
    name: 'JPMorgan Chase xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z',
    symbol: 'LINx',
    name: 'Linde xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA',
    symbol: 'MRVLx',
    name: 'Marvell xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC',
    symbol: 'MAx',
    name: 'Mastercard xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2',
    symbol: 'MCDx',
    name: "McDonald's xStock",
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2',
    symbol: 'MDTx',
    name: 'Medtronic xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X',
    symbol: 'MRKx',
    name: 'Merck xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu',
    symbol: 'METAx',
    name: 'Meta xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ',
    symbol: 'MSTRx',
    name: 'MicroStrategy xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ',
    symbol: 'QQQx',
    name: 'Nasdaq xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL',
    symbol: 'NFLXx',
    name: 'Netflix xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n',
    symbol: 'NVOx',
    name: 'Novo Nordisk xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh',
    symbol: 'NVDAx',
    name: 'NVIDIA xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6',
    symbol: 'OPENx',
    name: 'OPEN xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL',
    symbol: 'ORCLx',
    name: 'Oracle xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4',
    symbol: 'PLTRx',
    name: 'Palantir xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF',
    symbol: 'PEPx',
    name: 'PepsiCo xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw',
    symbol: 'PFEx',
    name: 'Pfizer xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3',
    symbol: 'PMx',
    name: 'Philip Morris xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV',
    symbol: 'PGx',
    name: 'Procter & Gamble xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg',
    symbol: 'HOODx',
    name: 'Robinhood xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN',
    symbol: 'CRMx',
    name: 'Salesforce xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W',
    symbol: 'SPYx',
    name: 'SP500 xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp',
    symbol: 'TBLLx',
    name: 'TBLL xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB',
    symbol: 'TSLAx',
    name: 'Tesla xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57',
    symbol: 'TMOx',
    name: 'Thermo Fisher xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc',
    symbol: 'TQQQx',
    name: 'TQQQ xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe',
    symbol: 'UNHx',
    name: 'UnitedHealth xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9',
    symbol: 'VTIx',
    name: 'Vanguard xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p',
    symbol: 'Vx',
    name: 'Visa xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci',
    symbol: 'WMTx',
    name: 'Walmart xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
  {
    mint: 'XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX',
    symbol: 'MSFTx',
    name: 'Microsoft xStock',
    decimals: 9,
    price: 0,
    change24h: 0,
    marketCap: 0,
    volume24h: 0,
  },
]

export function StonksContent() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null)
  const [stocks, setStocks] = useState<IStockInfo[]>(STOCK_DATA)

  // Compose ids for v3
  const priceIds = useMemo(
    () =>
      stocks
        .map((s) => s.mint)
        .filter((m) => m && m !== USDC_MINT)
        .join(','),
    [stocks]
  )

  // Fetch v3 prices for all at once (every minute)
  const { data: v3Data } = useQuery<
    Record<string, { usdPrice: number; priceChange24h?: number }>
  >({
    endpoint: 'jupiter/price-v3',
    queryParams: priceIds ? { ids: priceIds } : undefined,
    skip: !priceIds,
    config: {
      refreshInterval: 60000,
      dedupingInterval: 10000,
      keepPreviousData: true,
      revalidateOnFocus: false,
      revalidateIfStale: false,
    },
  })

  // Update stock data every minute (force re-render)
  useEffect(() => {
    const interval = setInterval(() => {
      setStocks((prev) => [...prev])
    }, 60000)
    return () => clearInterval(interval)
  }, [])

  const handleCardClick = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index)
  }

  return (
    <div className="flex-1 px-2 sm:px-4 md:px-6 py-4 md:py-6 max-w-7xl mx-auto w-full">
      {/* Header */}
      <div className="mb-4 md:mb-6">
        <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground mb-1 md:mb-2">
          Stonks 📈
        </h1>
        <p className="text-sm md:text-base text-muted-foreground">
          Trade tokenized stocks on Solana
        </p>
      </div>

      {/* Stock List */}
      <div className="space-y-2 md:space-y-3">
        {stocks.map((stock, index) => (
          <StonkCard
            key={stock.mint || stock.symbol}
            stock={stock}
            isExpanded={expandedIndex === index}
            onClick={() => handleCardClick(index)}
            precomputedUsdPrice={v3Data?.[stock.mint]?.usdPrice ?? null}
          />
        ))}
      </div>
    </div>
  )
}
